// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// pst_S_cpp
NumericVector pst_S_cpp(const NumericMatrix& par, const std::string& dist, const NumericVector& X, const IntegerVector& d, const NumericVector& L, const NumericVector& R, const double tol);
RcppExport SEXP _BayesTSM_pst_S_cpp(SEXP parSEXP, SEXP distSEXP, SEXP XSEXP, SEXP dSEXP, SEXP LSEXP, SEXP RSEXP, SEXP tolSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericMatrix& >::type par(parSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type dist(distSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const IntegerVector& >::type d(dSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type L(LSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type R(RSEXP);
    Rcpp::traits::input_parameter< const double >::type tol(tolSEXP);
    rcpp_result_gen = Rcpp::wrap(pst_S_cpp(par, dist, X, d, L, R, tol));
    return rcpp_result_gen;
END_RCPP
}
// pst_X_cpp
NumericVector pst_X_cpp(const NumericMatrix& par, const std::string& dist, const NumericVector& S, const IntegerVector& d, const NumericVector& L, const NumericVector& R, const double tol);
RcppExport SEXP _BayesTSM_pst_X_cpp(SEXP parSEXP, SEXP distSEXP, SEXP SSEXP, SEXP dSEXP, SEXP LSEXP, SEXP RSEXP, SEXP tolSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericMatrix& >::type par(parSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type dist(distSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type S(SSEXP);
    Rcpp::traits::input_parameter< const IntegerVector& >::type d(dSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type L(LSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type R(RSEXP);
    Rcpp::traits::input_parameter< const double >::type tol(tolSEXP);
    rcpp_result_gen = Rcpp::wrap(pst_X_cpp(par, dist, S, d, L, R, tol));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_BayesTSM_pst_S_cpp", (DL_FUNC) &_BayesTSM_pst_S_cpp, 7},
    {"_BayesTSM_pst_X_cpp", (DL_FUNC) &_BayesTSM_pst_X_cpp, 7},
    {NULL, NULL, 0}
};

RcppExport void R_init_BayesTSM(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
