#' Generate interval-censored three-state screening data
#'
#' Simulates interval-censored three-state screening data with covariates,
#' latent transition times, screening visit schedules, and observed event
#' categories as described by Klausch et al. (2023).
#'
#' @param n Integer; number of individuals to simulate.
#' @param p Integer; number of multivariate normally distributed covariates.
#' @param p.discrete Integer; number of additional discrete covariates. Currently
#'   only `0` or `1` is supported.
#' @param r Common correlation parameter used for the continuous covariates.
#' @param s Standard deviation used for each continuous covariate.
#' @param sigma.X Scale parameter for the first transition model (`X`).
#' @param mu.X Intercept for the first transition model (`X`).
#' @param beta.X Numeric vector of regression coefficients for the continuous and
#'   discrete covariates in the first transition model. Should have length equal
#'   to the total number of covariates.
#' @param sigma.S Scale parameter for the second transition model (`S`).
#' @param mu.S Intercept for the second transition model (`S`).
#' @param beta.S Numeric vector of regression coefficients for the continuous and
#'   discrete covariates in the second transition model. Should have length equal
#'   to the total number of covariates.
#' @param cor.X.S Correlation between the latent errors of `X` and `S` when
#'   `dist.X = "bv-lognormal"`.
#' @param Tmax Integer; maximum number of screening visits generated per
#'   individual.
#' @param v.min Minimum gap between two consecutive screening visits.
#' @param v.max Maximum gap between two consecutive screening visits.
#' @param mean.rc Mean of the exponential random censoring time distribution.
#' @param dist.X Character string specifying the distribution used to simulate
#'   `X`. Supported values are `"weibull"`, `"loglog"`, `"lognormal"`, and
#'   `"bv-lognormal"`. If `dist.X = "bv-lognormal"`, then `X` and `S` are
#'   simulated jointly from a bivariate log-normal model with latent-error
#'   correlation `cor.X.S`, and the value of `dist.S` is ignored.
#' @param dist.S Character string specifying the distribution used to simulate
#'   `S`. Supported values are `"weibull"`, `"loglog"`, and `"lognormal"`. This
#'   argument is ignored when `dist.X = "bv-lognormal"`.
#' @param do.b.XS Logical; whether to include a dependence term proportional to
#'   `log(X)` in the linear predictor for `S`.
#' @param b.XS Numeric coefficient multiplying `log(X)` when `do.b.XS = TRUE`.
#'
#' @return A `data.frame` with one row per individual. It contains:
#' \describe{
#'   \item{`L`}{Left endpoint of the observed event interval.}
#'   \item{`R`}{Right endpoint of the observed event interval. Right-censored
#'   observations have `R = Inf`.}
#'   \item{`d`}{Observed event category.}
#'   \item{`X`}{Simulated latent time from baseline to the first transition.}
#'   \item{`S`}{Simulated latent time from the first to the second transition.}
#'   \item{`Z`}{Simulated covariates, included when `p > 0`.}
#' }
#'
#' @details
#' The function first simulates covariates from a multivariate normal
#' distribution with exchangeable correlation structure and optional additional
#' Bernoulli covariate. Given these covariates, latent transition times `X` and
#' `S` are generated from accelerated failure time models on the log-time scale.
#'
#' The total time to the second event is `X + S`. Individuals are then assigned
#' a sequence of screening visit times. The first screening time is sampled
#' uniformly on the interval from `v.min` to `v.max`, and each subsequent
#' screening time is generated by adding a uniform increment between `v.min` and
#' `v.max` to the previous visit time. Follow-up is administratively censored at
#' a random censoring time generated from an exponential distribution with mean
#' `mean.rc`.
#'
#' The observed data are constructed from the screening interval in which the
#' first detected transition occurs. The event indicator `d` equals `2` if the
#' first transition time `X` falls in the observed interval but the second event
#' time `X + S` does not; `d` equals `3` if both transitions have occurred by the
#' same observed screening interval; and `d` equals `1` if no event is observed
#' during follow-up, in which case `R = Inf`.
#'
#' When `do.b.XS = TRUE`, the second transition time depends additionally on
#' `log(X)` through coefficient `b.XS`. This induces dependence between the two
#' transition times beyond the shared covariate effects. Alternatively, when
#' `dist.X = "bv-lognormal"`, both `X` and `S` are generated jointly from a
#' bivariate log-normal construction with correlation `cor.X.S`; in that case
#' the separate specification through `dist.S` is overridden.
#'
#' This function is primarily intended for simulation studies, examples, and
#' testing of the model-fitting functions in the package.
#'
#' @examples
#' dat = gendat(
#'               n = 1000,  # Sample size
#'               p = 2,     # Number of normal distributed covariates
#'               r = 0,     # Correlation of the covariates
#'               sigma.X = 0.3,         # True scale parameter
#'               mu.X    = 2,           # True intercept parameter
#'               beta.X  = c(0.5,0.5),  # True slope parameters
#'               sigma.S = 0.5,         # True scale parameter
#'               mu.S    = 1,           # True intercept parameters
#'               beta.S  = c(0.5,0.5),  # True slope parameters
#'               dist.X  = 'weibull',   # Distribution of X
#'               dist.S  = 'weibull',   # Distribution of S
#'               v.min   = 1,           # Min time between screening moments
#'               v.max   = 5,           # Max time between screening moments
#'               Tmax    = 2e2,         # Max number of screening times
#'               mean.rc = 10           # Mean time to right censoring
#'             )
#'
#' @export
gendat = function(n, p = 3, p.discrete = 0, r=.1, s = 1,
                  sigma.X=1/2, mu.X = 1, beta.X = NULL,
                  sigma.S=1/2, mu.S = 1, beta.S = NULL,
                  cor.X.S = 0,
                  Tmax = 20, v.min = 1, v.max = 6, mean.rc = 40,
                  dist.X='weibull', dist.S='weibull',
                  do.b.XS = F, b.XS = NULL){

  if(p ==0){
    beta.X = as.matrix(mu.X)
    beta.S = as.matrix(mu.S)
  }   else{
  beta.X = as.matrix(c(mu.X, beta.X))
  beta.S = as.matrix(c(mu.S, beta.S))
  }

  # Sim Z
  R = matrix(r, p, p)
  diag(R) =  1
  S = rep(s, p)
  Sigma = cor2cov(R, S)
  if(p>0) {Z = mvrnorm(n, mu = rep(0,p), Sigma)} else Z = NULL
  # Sim discrete Z
  if(p.discrete == 1){
    Z.discrete = rbinom(n, 1, 0.5)
    Z = cbind( Z, Z.discrete)
    colnames(Z) = paste(1:ncol(Z))
  }
  Z1 = cbind( as.matrix(rep(1,n)),Z)

  # Sim.X
  if( dist.X=='weibull' | dist.X=='loglog' | dist.X=='lognormal' ){
    if(dist.X=='weibull')    e.X = r.ev(n)
    if(dist.X=='loglog')     e.X = rlog(n)
    if(dist.X=='lognormal')  e.X = rnorm(n)
    X = Z1 %*% beta.X + sigma.X * e.X # log surv times
    X = exp(X) # surv times
    X  = as.numeric(X)
  }
  # Sim.S
  if( dist.S=='weibull' | dist.S=='loglog' | dist.S=='lognormal' ){
    if(dist.S=='weibull')   e.S = r.ev(n)
    if(dist.S=='loglog')    e.S = rlog(n)
    if(dist.S=='lognormal') e.S = rnorm(n)
    S = Z1 %*% beta.S + sigma.S * e.S # log surv times
    if(do.b.XS){
      #logstdX = scale(X)
      S = Z1 %*% beta.S + b.XS * log(X) + sigma.S * e.S # log surv times
    }
    S = exp(S) # surv times
    S = as.numeric(S)
  }

  if(dist.X=='bv-lognormal'){
    Sigma.e  = matrix( c(1, cor.X.S, cor.X.S, 1), 2, 2)
    e = mvrnorm(n, c(0,0), Sigma.e)
    X = Z1 %*% rbind(mu.X, beta.X) + sigma.X * e[,1] # log surv times
    S = Z1 %*% rbind(mu.S, beta.S) + sigma.S * e[,2] # log surv times
    X = as.numeric(exp(X))
    S = as.numeric(exp(S))
  }

  # Create total time
  XS = as.numeric(X+S)  # Total time from baseline to event 2

  # Generate screening sequences
  t.rc = rexp(n, 1/mean.rc ) #runif(n, start.rc, vmax*(visitdist+leniancy))
  V = as.matrix(runif(n, v.min, v.max ))
  for(i in 2:Tmax){
    V = cbind(V, runif(n, V[,(i-1)]+v.min, V[,(i-1)]+v.max ))
  }
  t.rc = V[,1] + t.rc
  i = apply(V < t.rc, 1, sum)
  t.rc = apply( cbind(i, V), 1, function(x) x[x[1]+1] )
  t.rc = matrix( rep( t.rc, Tmax), nrow = n, ncol = Tmax)
  V    = (V < t.rc) * V + (V >= t.rc) * t.rc
  V    = cbind(0, V)

  # Find indices of events
  ind.h  = rowSums(V < X) # Last healthy time index
  ind.x  = ind.h+1        # First stage 1
  ind.xs = rowSums(V < XS) + 1 # First stage 2
  ind.x[ind.x>ncol(V)] = ncol(V)

  # Define delta (event)
  d = rep(-99,n)
  d[ind.x < ind.xs ]  = 2
  d[ind.x == ind.xs  & ind.xs != (ncol(V)+1)] = 3
  d[ind.h == ind.x]  = 1

  # Define left and right interval bound
  L = V[ cbind(1:nrow(V), ind.h) ]
  R = V[ cbind(1:nrow(V), ind.x) ]
  R[ ind.h == ind.x ] = Inf

  if(p>0) dat = data.frame(L=L, R=R, d=d, X=X, S=S, Z=Z)
  if(p==0) dat = data.frame(L=L, R=R, d=d, X=X, S=S)

  return(dat)
}
