# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Draw latent S values
#'
#' @param par Numeric matrix of parameters.
#' @param dist Distribution name.
#' @param C Numeric vector.
#' @param d Integer vector.
#' @param L Numeric vector.
#' @param R Numeric vector.
#' @param tol Tolerance.
#' @return Numeric vector.
#' @noRd
pst_S_cpp <- function(par, dist, X, d, L, R, tol = 1e-8) {
    .Call(`_BayesTSM_pst_S_cpp`, par, dist, X, d, L, R, tol)
}

pst_X_cpp <- function(par, dist, S, d, L, R, tol = 1e-8) {
    .Call(`_BayesTSM_pst_X_cpp`, par, dist, S, d, L, R, tol)
}

